WSO2 Font integration and Custom components.
wso2/carbon-device-mgt pull request #1001
Opened 2017-09-28 17:16 UTC by menakaj

2017-09-28 17:46 UTC, sinthuja commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/src/main/resources/publisher/src/components/Application/Edit/Base/baseLayout.css
> -    border: 1px solid #ccc;
The css classes files should go into the public directory right? Else we can't change the theming..

2017-09-28 17:47 UTC, sinthuja commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/src/main/resources/publisher/src/components/UIComponents/FloatingButton/FloatingButton.jsx
> +        console.log("click");
Need to remove all console.log. Please do have a todo cleanup all these.

2017-09-28 17:47 UTC, sinthuja commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/src/main/resources/publisher/src/index.css
> -    background-color: #BDBDBD;
Again, we need to move all css to public folder.

2017-09-28 17:49 UTC, sinthuja requested changes
We shouldn't have the css files within the main source, rather we should have it in the public directory. else we can't have theming support.

2017-09-28 19:43 UTC, menakaj commented
All the internal css were extracted and moved to external css file.

2017-09-28 20:31 UTC, menakaj commented
TODOs were added to remove console logs. 
Method names were changed to meaningful names.
Cleaned up the code base.

2017-09-29 07:07 UTC, sinthuja approved these changes

2017-09-29 07:07 UTC, merged