Unit tests for MQTTPushNotificationProvider
wso2/carbon-device-mgt pull request #1078
Opened 2017-10-20 06:45 UTC by GDLMadushanka

## Purpose
> Unit tests for MQTTPushNotificationProvider

## Goals
> Improve unit test coverage

## Automation tests
 - Unit tests 
   > 80%, 70%

## Test environment
> JDK 8 and Ubuntu 16.04

2017-10-20 06:49 UTC, Megala21 commented on components/device-mgt-extensions/org.wso2.carbon.device.mgt.extensions.push.notification.provider.mqtt/src/test/resources/conf/carbon.xml
> +  ~ Copyright 2005-2017 WSO2 Inc. (http://wso2.com)
License header should have only the current year

2017-10-20 06:49 UTC, Megala21 commented on components/device-mgt-extensions/org.wso2.carbon.device.mgt.extensions.push.notification.provider.mqtt/src/test/resources/log4j.properties
> +# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
It should be 2017

2017-10-20 06:50 UTC, Megala21 requested changes
Since you are adding new test cases for mqtt, shall we add the exec file path to the pom of test-coverage

2017-10-20 07:07 UTC, Megala21 approved these changes

2017-10-20 07:07 UTC, merged

2018-03-16 08:15 UTC, pamod commented on components/device-mgt-extensions/org.wso2.carbon.device.mgt.extensions.push.notification.provider.mqtt/src/test/java/org/wso2/carbon/device/mgt/extensions/push/notification/provider/mqtt/MQTTBasedPushNotificationProviderTest.java
> +    Unit tests for MQTTBasedPushNotificationProvider class
Extra space ?

2018-03-16 08:22 UTC, pamod commented on components/device-mgt-extensions/org.wso2.carbon.device.mgt.extensions.push.notification.provider.mqtt/src/test/java/org/wso2/carbon/device/mgt/extensions/push/notification/provider/mqtt/MQTTNotificationStrategyTest.java
> +        if (System.getProperty("carbon.home") == null) {
This method is duplicated  with MQTTBasedPushNotificationProviderTest#initializeCarbonContext() can't we introduce a util for this ?

2018-03-16 08:23 UTC, pamod commented on components/device-mgt-extensions/org.wso2.carbon.device.mgt.extensions.push.notification.provider.mqtt/src/test/java/org/wso2/carbon/device/mgt/extensions/push/notification/provider/mqtt/MQTTNotificationStrategyTest.java
> +                System.setProperty("carbon.home", file.getAbsolutePath());
Can we define a constant for "carbon.home" ?