Updated the last-known api to be able to return a number of records.
wso2/carbon-device-mgt pull request #1193
Opened 2018-02-23 03:42 UTC by lashanfaliq95

## Purpose
> To be able to get a number of recent records so that a chart can be updated based on those records/

## Goals
> The new last-known API will return 1 record if no limit is passed or it will return the number of records we pass as the limit.
## Approach
> Last known API was updated so that it will be backward compatible , the limit parameter is optional so if a limit parameter is not passed it will act as i was before. But if a limit parameter is passed then it will return that limit of records.

## User stories
> N/A

## Release note
> N/A

## Documentation
> N/A

## Training
>N/A

## Certification
> N/A

## Marketing
>N/A

## Automation tests
 - Unit tests 
   >N/A
 - Integration tests
   >N/A

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Samples
> N/A
## Related PRs
> N/A

## Migrations (if applicable)
> N/A

## Test environment
>N/A
 
## Learning
> N/A

2018-02-23 10:02 UTC, madawas requested changes

2018-02-23 10:02 UTC, madawas commented on components/device-mgt/org.wso2.carbon.device.mgt.api/src/main/java/org/wso2/carbon/device/mgt/jaxrs/service/impl/DeviceEventManagementServiceImpl.java
> +            else{
@lashanfaliq95 There is a formatting issue here.  Please apply the code formatting to all the files you have changed.

2018-02-23 10:02 UTC, madawas commented on components/device-mgt/org.wso2.carbon.device.mgt.api/src/main/java/org/wso2/carbon/device/mgt/jaxrs/service/impl/DeviceEventManagementServiceImpl.java
> +
@lashanfaliq95 Remove the unnecessary lines

2018-02-23 10:10 UTC, lasanthaDLPDS requested changes

2018-02-23 10:10 UTC, lasanthaDLPDS commented on components/device-mgt/org.wso2.carbon.device.mgt.api/src/main/java/org/wso2/carbon/device/mgt/jaxrs/service/api/DeviceEventManagementService.java
> +
@lashanfaliq95 Remove the unnecessary lines

2018-03-03 18:00 UTC, lasanthaDLPDS approved these changes

2018-03-03 19:00 UTC, rasika approved these changes

2018-03-14 02:25 UTC, madawas approved these changes

2018-03-14 03:47 UTC, charithag requested changes

2018-03-14 03:47 UTC, charithag commented on components/device-mgt/org.wso2.carbon.device.mgt.api/src/main/java/org/wso2/carbon/device/mgt/jaxrs/service/api/DeviceEventManagementService.java
> +    Response getLastKnownData(@ApiParam(name = "deviceId", value = "id of the device ", required = false)
According to the implementation, device id is a required field.

2018-03-14 03:47 UTC, charithag commented on components/device-mgt/org.wso2.carbon.device.mgt.api/src/main/java/org/wso2/carbon/device/mgt/jaxrs/service/api/DeviceEventManagementService.java
> +                              @ApiParam(name = "type", value = "name of the device type", required = false)
According to the implementation, device type is a required field.

2018-03-14 03:47 UTC, charithag commented on components/device-mgt/org.wso2.carbon.device.mgt.api/src/main/java/org/wso2/carbon/device/mgt/jaxrs/service/impl/DeviceEventManagementServiceImpl.java
> +     * Returns the last know data point of the device type or last known data points upto the limit.
Change method comment as below.
> Returns last known data points up to the limit if limit is specified. Otherwise returns last known data point.

2018-03-14 09:42 UTC, charithag approved these changes

2018-03-14 09:44 UTC, merged