Fixed https://github.com/wso2/carbon-device-mgt/issues/1194
wso2/carbon-device-mgt pull request #1197
Opened 2018-02-24 10:59 UTC by Arcane94

## Purpose
> Resolving the issue of defined geofence area changing upon definition of another one with the same name. Resolves #1194.

## Goals
> Returning a 'Bad Request' response when a user tries to define an alert with a name of already existing alert.

## Approach
> Attempting to get the execution plan for the geo alert name, that user enters upon definition. If it doesn't exist, thrown AxisFault exception is caught. Then the registry is updated and a new alert is deployed. But if the execution plan already exists, an AlertAlreadyExist exception is thrown. 

## User stories
> As a user I'm not allowed to define a geo alert with a name of an already existing one.

## Release note
> Fixing an issue when defining geo alerts with the same name.

## Documentation
> N/A

## Training
> N/A

## Certification
> N/A

## Marketing
> N/A

## Automation tests
 - Unit tests 
   > Updated already existing ones
 - Integration tests
   > N/A

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Samples
> N/A

## Related PRs
> N/A

## Migrations (if applicable)
> N/A

## Test environment
> JDK version: java 1.8.0_144
Operating System: Linux Ubuntu
Databases: H2
Browser version: Google Chrome 62.0.3202.89
 
## Learning
> N/A

2018-02-28 08:59 UTC, madawas requested changes

2018-02-28 08:59 UTC, madawas commented on components/device-mgt/org.wso2.carbon.device.mgt.common/src/main/java/org/wso2/carbon/device/mgt/common/geo/service/AlertAlreadyExist.java
> + * Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
@Arcane94 Since this is a newly added file, year should be 2018

2018-03-03 19:03 UTC, rasika approved these changes

2018-03-04 02:19 UTC, madawas approved these changes

2018-03-04 02:56 UTC, charithag requested changes

2018-03-04 02:56 UTC, charithag commented on components/device-mgt/org.wso2.carbon.device.mgt.common/src/main/java/org/wso2/carbon/device/mgt/common/geo/service/AlertAlreadyExist.java
> +public class AlertAlreadyExist extends Exception {
Classes for exceptions generally identified with Exception or Fault suffix. So this class should be renamed as AlertAlreadyExistException.

2018-03-04 02:56 UTC, charithag commented on components/device-mgt/org.wso2.carbon.device.mgt.core/src/main/java/org/wso2/carbon/device/mgt/core/geo/service/GeoLocationProviderServiceImpl.java
> +                            throw new AlertAlreadyExist("Execution plan with this name already exists");
This message should contain the executionPlanName. So message should be as follows.
"Execution plan already exists with name '" + executionPlanName + "'"

2018-03-04 02:56 UTC, charithag commented on components/device-mgt/org.wso2.carbon.device.mgt.core/src/main/java/org/wso2/carbon/device/mgt/core/geo/service/GeoLocationProviderServiceImpl.java
> +                        updateRegistry(getRegistryPath(alertType, identifier, alert.getQueryName()), identifier, content,
Why you are updating registry with the alert upon axisFault?

2018-03-04 02:56 UTC, charithag commented on components/device-mgt/org.wso2.carbon.device.mgt.core/src/main/java/org/wso2/carbon/device/mgt/core/geo/service/GeoLocationProviderServiceImpl.java
> +                        eventprocessorStub.deployExecutionPlan(parsedTemplate);
Why you are deploying execution plan upon axisFault? Also please log the axisFault here with appropriate log level (warning or error)

2018-03-14 02:04 UTC, charithag approved these changes

2018-03-14 04:25 UTC, merged