Device cloud related ui improvments
wso2/carbon-device-mgt pull request #892
Opened 2017-08-10 11:48 UTC by Kamidu

2017-08-11 09:14 UTC, rasika requested changes

2017-08-11 09:14 UTC, rasika commented on components/device-mgt/org.wso2.carbon.device.mgt.ui/src/main/resources/jaggeryapps/devicemgt/app/modules/oauth/token-protected-service-invokers.js
> +        if (devicemgtProps["isCloud"]) {
Shall we discuss on this? IMO this will flood the logs.

2017-08-11 09:36 UTC, madawas commented on components/device-mgt/org.wso2.carbon.device.mgt.ui/src/main/resources/jaggeryapps/devicemgt/app/modules/oauth/token-protected-service-invokers.js
> +        if (devicemgtProps["isCloud"]) {
@rasika IMO these logs were introduced for auditing purposes and to speed up the debugging process.

2017-08-11 10:05 UTC, Kamidu commented on components/device-mgt/org.wso2.carbon.device.mgt.ui/src/main/resources/jaggeryapps/devicemgt/app/modules/oauth/token-protected-service-invokers.js
> +        if (devicemgtProps["isCloud"]) {
This was enabled as instructed by cloud team. We are in the process of enabling audit logs through out the iot server then we can remove these

2017-08-15 13:59 UTC, rasika approved these changes

2017-08-15 14:00 UTC, merged