App Publisher UI : Basic Layout.
wso2/carbon-device-mgt pull request #902
Opened 2017-08-19 20:16 UTC by menakaj

2017-08-20 18:12 UTC, Megala21 requested changes

2017-08-20 18:12 UTC, Megala21 commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please add the license header

2017-08-20 18:12 UTC, Megala21 commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/pom.xml
> +                            <importFeatures>
Why do we have empty blocks? Please remove them

2017-08-20 18:12 UTC, Megala21 commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/pom.xml
> +</project>
Add an extra line at the end of the file.

2017-08-20 18:12 UTC, Megala21 commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/pom.xml
> +                    <!--</execution>-->
Why do we have commented code ? Please clear them

2017-08-20 18:12 UTC, Megala21 commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/src/main/resources/publisher/public/index.html
> +<!doctype html>
Don't we need the license?

2017-08-20 18:12 UTC, Megala21 commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/src/main/resources/publisher/src/App.js
> +class Base extends Component {
Can we add comments to indicate what is the purpose of each component, if React supports that ?

2017-08-20 18:12 UTC, Megala21 commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/src/main/resources/publisher/src/actions/ApplicationActions.js
> +/*
What is the purpose of having files only with license header? Are they needed ?

2017-08-20 18:12 UTC, Megala21 commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/src/main/resources/publisher/src/components/Application/Forms/Step1.js
> +    onChangeStore = (event, index, value) => {
I think it is better to add come comments for user-defined functions.

2017-08-20 18:12 UTC, Megala21 commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/src/main/resources/publisher/src/components/Application/Forms/Step3.js
> +export default Step3;
Please add an extra line at the end of the file. Please change it in other places as well.

2017-08-20 18:12 UTC, Megala21 commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/src/main/resources/publisher/webpack.config.js
> +var path = require('path');
Missing License header

2017-08-20 18:12 UTC, Megala21 commented on components/application-mgt/org.wso2.carbon.device.application.mgt.store.ui/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
License header is missing here too.

2017-08-20 18:12 UTC, Megala21 commented on components/application-mgt/org.wso2.carbon.device.application.mgt.store.ui/pom.xml
> +        <!--<artifactId>org.wso2.carbon.apimgt.publisher.feature</artifactId>-->
Please remove the commented code

2017-08-20 18:12 UTC, Megala21 commented on components/application-mgt/org.wso2.carbon.device.application.mgt.store.ui/pom.xml
> +                    <!-- 'npm run clean' which is run in clean lifecycle needs 'rimraf' node module.
Why do we have commented code?

2017-08-20 18:12 UTC, Megala21 commented on features/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui.feature/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
License header is missing

2017-08-21 08:47 UTC, menakaj commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/pom.xml
> +                            <importFeatures>
Removed the empty blocks.

2017-08-21 08:47 UTC, menakaj commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/src/main/resources/publisher/public/index.html
> +<!doctype html>
License added.

2017-08-21 08:48 UTC, menakaj commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/src/main/resources/publisher/src/actions/ApplicationActions.js
> +/*
Added the base content for the JS files.

2017-08-21 17:10 UTC, Megala21 commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/pom.xml
> +                    </execution>
bundles, importBundles are still empty

2017-08-21 17:10 UTC, Megala21 commented on components/application-mgt/org.wso2.carbon.device.application.mgt.publisher.ui/src/main/resources/publisher/public/index.html
> +~ Copyright (c) 2014, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
License year is wrong

2017-08-22 10:30 UTC, merged